model:
  name: "Surendra-Aitest/phi2-env-factors-merged" # Set the desired LLM
  max_length: 1024 # Reduced default length
  temperature: 0.7 # Restore original temp
  top_p: 0.9

# Embedding model configuration
embedding:
  model_name: "sentence-transformers/all-mpnet-base-v2" # Use a 768-dim model
  dimension: 768 # Specify dimension

vector_store:
  qdrant:
    host: "localhost"
    port: 6333
    collection_name: "emission_factors"
    vector_size: 768 # Match embedding model dimension
    distance: "Cosine"

graph_db:
  neo4j:
    uri: "bolt://localhost:7687" # Pointing to default Docker Neo4j
    user: "neo4j"
    password: "carbon_ef_secure"
    database: "neo4j"

# Cache section can be restored if AgentFramework uses it
cache:
  redis:
    host: "localhost"
    port: 6379
    ttl: 3600  
    max_size: 10000

api:
  host: "0.0.0.0"
  port: 8000
  workers: 2 # Reduced workers for simpler setup
  timeout: 60

web:
  streamlit:
    port: 8501
    theme:
      primaryColor: "#FF4B4B"
      backgroundColor: "#FFFFFF"
      secondaryBackgroundColor: "#F0F2F6"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s" 
